import Head from 'next/head'
import Image from 'next/image'
import Section from '../common/components/elements/Section/Section'
import Navbar from '../common/components/navbar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Snippet Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Section position={"original"} />
        <Section position={"result"} />
      </main>
    </div>
  )
}
